apiVersion: apps/v1
kind: Deployment
metadata:
  name: meubles-by-mi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meubles-by-mi
  template:
    metadata:
      labels:
        app: meubles-by-mi
    spec:
      containers:
        - name: meubles-by-mi
          image: gcr.io/gobc-407614/meubles-by-mi:{DOCKER_IMAGE_TAG}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: meubles-by-mi
spec:
  type: NodePort
  selector:
    app: meubles-by-mi
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000
